Repository hekzam/markers-eval-25, pull requests merged in 2025-03, with the labels that each got.

#10 Mise en place d'une interface de benchmarking via un CLI
  CMakeLists.txt
  README.md
  create-copie.sh
  include/benchmark.hpp
  run_benchmark.sh
  src/benchmark.cpp
  src/command-line-interface/command_line_interface.cpp
  src/command-line-interface/command_line_interface.h
  src/expl_pars.cpp
  src/external-tools/create_copy.cpp
  src/external-tools/create_copy.h
  src/typst_interface.cpp
  src/utils/benchmark_helper.cpp
  src/utils/benchmark_helper.h
  src/utils/draw_helper.cpp
  src/utils/draw_helper.h
  src/utils/parser_helper.cpp
  src/utils/parser_helper.h
Labels: benchmark

#8 Visualisation et interprétation statistiques des données CSV
  stats-analysis/README.md
  stats-analysis/figures.r
Labels: benchmark

#11 Modification mineure du module de Simulation
  tools/pdf_noiser/printer_emulator.py
Labels: simulation

#14 Eviter le téléchargement automatique de Zxing
  .github/workflows/linux-test.yml
  .vscode/settings.json
  CMakeLists.txt
Labels: enhancement

#13 Intégration du simulateur d’impression via cpp
  .vscode/settings.json
  CMakeLists.txt
  src/benchmark.cpp
  src/expl_pars.cpp
  src/modifier.cpp
  src/parser/aruco_parser.cpp
  src/parser/circle_parser.cpp
  src/parser/qrcode_empty_parser.cpp
  src/utils/math_utils.cpp
  src/utils/math_utils.h
  src/utils/parser_helper.cpp
Labels: simulation

#12 Ajout d'un parseur de forme et amélioration du cas où seulement 3 marqueurs sur 4 sont détectés
  src/expl_pars.cpp
  src/parser/circle_parser.cpp
  src/parser/circle_parser.h
  src/parser/custom_marker_parser.h
  src/parser/qrcode_empty_parser.cpp
  src/parser/qrcode_empty_parser.h
  src/parser/qrcode_parser.cpp
  src/parser/qrcode_parser.h
  src/parser/shape_parser.cpp
  src/parser/shape_parser.h
  src/utils/math_utils.cpp
  src/utils/parser_helper.cpp
Labels: parser
